server:
  port: 18080
spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service-route
              uri: lb://USER-SERVICE
              predicates:
              - Path=/api/users/**
              filters:
              - TokenRelay=
            - id: order-service-route
              uri: lb://ORDER-SERVICE
              predicates:
              - Path=/api/orders/**
              filters:
              - TokenRelay=

